name: Configuration Variables

on: 
  push:
    branches: [ "main" ]
  pull-request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  cloud: google-cloud

jobs:
  greeting_configuration:

    runs-on: ubuntu-latest
    env:
      NAME: Mansoor
    steps: 
      - uses: actions/checkout@v4
      - name: Configuration Variables
        run: echo "Hello $NAME, the $cloud project ID is ${{ vars.PROJECT_ID }}"
        env:
          Hello: World
