name: Context Variables

on:
  push:
    brnches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing Context Variables"
      - uses: actions/checkout@v4
        run: echo "Repository Name is ${{ github.reposiory }}"
          

